FROM node:14.3.0-alpine as builder
WORKDIR /usr/app
ENV PATH=/usr/app/node_modules/.bin:$PATH
COPY package.json package.json
RUN npm install
COPY . .
RUN ng build --build-optimizer --output-path=dist

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf


